services:
  backend:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /home/debian/static/mnemosyne:/enysomenm/static
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: "postgres:16.3-alpine3.19"
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    # recommended by postgres
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-volume:
